# my workflow name is "test".
name: test

# restrict the condition of "test" workflow.
on:
  # the workflow happens when commits of main branch are pushed.
  push:
    branches: [ "main" ]
    
  # the workflow happens when pull requests of main branch are received.
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # the job operates in ubuntu os.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
      # print "Hello, world!" by shell script.
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          # print "test", and deploy.
          echo test, and deploy your project.
